[tool.poetry]
name = "skeleton-pyspark"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
tox = "^3.23.0"
Sphinx = "^3.5.4"
flake8 = "^3.9.1"
pytest = "^6.2.3"
pyspark = "^3.1.1"
mypy = "^0.812"
coverage = "^5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
